# Generated by Django 5.0.3 on 2024-04-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_tag_doc_paper_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='dictionary',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='doc',
            name='processed_text',
            field=models.JSONField(),
        ),
    ]
