# Generated by Django 5.0.3 on 2024-04-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_doc_dictionary_alter_doc_processed_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='dictionary',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
