# Generated by Django 5.0.3 on 2024-04-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_doc_dictionary'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='post',
            field=models.ManyToManyField(to='post.post'),
        ),
        migrations.DeleteModel(
            name='paper_tag',
        ),
    ]
