# Generated by Django 5.0.3 on 2024-04-07 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_tag_post_delete_paper_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='dictionary',
        ),
    ]
