# Generated by Django 5.0.3 on 2024-04-09 14:52

import django.core.validators
import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_remove_doc_dictionary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(upload_to='papers/', validators=[django.core.validators.FileExtensionValidator(['pdf']), post.models.validate_type]),
        ),
    ]
